# ===========================
# STAGE 1 — Build com Maven
# ===========================
FROM maven:3.9.6-eclipse-temurin-21 AS build

# Define o diretório onde está o microserviço
WORKDIR /app

# Copia tudo do projeto para dentro da imagem
COPY . .

# Entra na pasta onde está o pom.xml do serviço
WORKDIR /app/backend/soap_service

# Executa o build
RUN mvn clean package -DskipTests


# ===========================
# STAGE 2 — Runtime (JVM leve)
# ===========================
FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

# Copia o .jar gerado do stage anterior
COPY --from=build /app/backend/soap_service/target/*.jar app.jar

# Porta configurável
ARG PORT=8080
EXPOSE ${PORT}

ENTRYPOINT ["java", "-jar", "app.jar"]
