# Usando JDK 21
FROM eclipse-temurin:21-jdk-alpine

# Diretório de trabalho
WORKDIR /app

# Copia o JAR do microserviço
# Supondo que cada serviço seja buildado individualmente em target/
ARG JAR_FILE
COPY ${JAR_FILE} app.jar

# Expõe a porta (pode ser sobrescrita via docker-compose)
ARG PORT=8080
EXPOSE ${PORT}

# Entrada
ENTRYPOINT ["java","-jar","app.jar"]
